server.port=8080
spring.application.name=demo-service

# TODO (aapko khud add karna hai):
# Swagger enable/disable karne ke liye yahan properties add karo, jaise:
# springdoc.api-docs.enabled=true
 #springdoc.swagger-ui.enabled=true
